version: '3.7'
services:
  spark:
    image: "apache/spark:3.5.0-scala2.12-java11-r-ubuntu"
    command:
      - "/opt/spark/sbin/start-connect-server.sh"
      - "--conf"
      - "spark.driver.extraJavaOptions=-Divy.cache.dir=/tmp -Divy.home=/tmp"
      - "--packages"
      - "org.apache.spark:spark-connect_2.12:3.5.0"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "4040:4040"
      - "15002:15002"
